/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/kPkTqSHe4V0VkaCE/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#4a2e6c']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            visible={false}
            castShadow
            receiveShadow
            position={[-5.34, 129.7, -9.04]}
            rotation={[0, 0, -Math.PI]}
            scale={[0.57, 1, 1]}
          />
          <directionalLight
            name="Directional Light 2"
            castShadow
            intensity={1.06}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-373.854}
            shadow-camera-right={373.854}
            shadow-camera-top={373.854}
            shadow-camera-bottom={-373.854}
            position={[-99, 167.09, -240.59]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={2.6}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-112.935}
            shadow-camera-right={112.935}
            shadow-camera-top={112.935}
            shadow-camera-bottom={-112.935}
            position={[220.17, 167.09, 327.82]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
